# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-AWS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
env:
  EB-BUCKET-NAME: "buck-flask"
  APPLICATION-NAME: "flaskapp"
  EB-ENV-NAME: "Flaskapp-env"
  DEPLOY-PACKAGE-NAME: "flask-app-${{ github.sha }}.zip"
  AWS-REGION: "us-east-1"
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: clone-our-repo
        uses: actions/checkout@v2
      - name: create zip file
        run: zip -r ${{ env.DEPLOY-PACKAGE-NAME }} ./src -x *.git*
      - name: configure aws auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS-REGION }}
      - name: copy deployment package to s3
        run: aws s3 cp ${{ env.DEPLOY-PACKAGE-NAME }} s3:// ${{ env.EB-BUCKET-NAME }}/
    
        
      
  
  
